import type { Metadata } from "next";
import "./globals.css";
import {getUser} from "@/lib/auth/auth.service";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        Hello {getUser()}! <br/>
        {children}
      </body>
    </html>
  );
}
